### ISSUE TITLE
The solution button text color is kinda difficult to read

### ISSUE THREAD

**Issue by shalluv** [Leomotors/Com-POG#1]
<img width="100" alt="image" src="https://user-images.githubusercontent.com/42491719/184501238-3906770e-86d2-4e28-861a-d73f7b4550a8.png">

**Comment by leomotors** [comment]
I think (this button) color in dark theme is also ugly, what color should we use?

**Comment by shalluv** [comment]
How about these?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/42491719/184527812-a70190fa-c7ab-46cd-a459-57130a24f843.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/42491719/184527806-0d8a0907-c976-4723-8191-31bc41f18510.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/42491719/184527816-50a10a53-dc2e-4e8d-83c0-26336e120d7e.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/42491719/184527820-50ca6fa9-990d-4421-93a7-137497aaf51c.png">

**Comment by leomotors** [comment]
:orz:

Interesting idea, can you push the code so I can preview it?
