### ISSUE TITLE
Inconsistency of page layout position.

### ISSUE THREAD

**Issue by shalluv** [Leomotors/Com-POG#2]
If the main content div contains long enough text to make the scrollbar appears, it'll push everything a little bit to the left.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/42491719/184501695-3d6d5b54-fcae-444e-b704-049ea5022b6e.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/42491719/184501716-6ee412b6-a546-4f85-8e20-cb52a920fbe7.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/42491719/184501704-1932603f-7b5d-41b3-8dee-700656b8ddc0.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/42491719/184501710-186d26a7-4265-4dad-855f-1c89ff22c573.png">

The first and the third pictures have short text (no scrollbar), while the second and the fourth pictures have long text (have the scrollbar on the right).
 
They clearly didn't have the same layout position.
When it's come to quick page switching this might cause some nausea.

**Comment by leomotors** [comment]
This is Vitepress' Problem
https://vitepress.vuejs.org also has this issues

I don't think we can fix this unless we disable the scroll bar.
Any ideas?
